(function(){
'use strict';
const $=id=>document.getElementById(id);
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n(v));
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));

function getPerfumes(){try{const p=window.eval('perfumes');return Array.isArray(p)?p:[]}catch(e){console.error('Could not access collection',e);return[]}}
function setPerfumes(v){try{window.__perfumeBridgeValue=v;window.eval('perfumes=window.__perfumeBridgeValue');delete window.__perfumeBridgeValue}catch(e){console.error('Could not update collection',e)}}

window.startAdd=function(){if(typeof resetForm==='function')resetForm();try{window.eval('editingId=null')}catch(e){}if($('formTitle'))$('formTitle').textContent='Add a perfume';if($('saveBtn'))$('saveBtn').textContent='Save perfume';if(typeof go==='function')go('add')};
window.editPerfume=function(id){try{const list=getPerfumes(),p=list.find(x=>String(x.id)===String(id));if(!p){if(typeof toast==='function')toast('Perfume not found','error');return}window.__perfumeBridgeId=p.id;window.eval('editingId=window.__perfumeBridgeId');delete window.__perfumeBridgeId;['name','brand','type','occasion','cloneOf','imageUrl','quantity','quantityRemaining','year','price','rating','topNotes','heartNotes','baseNotes','accords','sourceUrl','notes'].forEach(k=>{const el=$(k);if(el)el.value=p[k]??''});if($('formTitle'))$('formTitle').textContent='Edit perfume';if($('saveBtn'))$('saveBtn').textContent='Update perfume';if(typeof updateCost==='function')updateCost();if(typeof go==='function')go('add')}catch(e){console.error(e);if(typeof toast==='function')toast('Could not open perfume for editing.','error')}};
window.savePerfume=async function(e){e.preventDefault();const form=$('perfumeForm');if(!form||!form.reportValidity())return;const q=n($('quantity')?.value),r=n($('quantityRemaining')?.value);if(r>q){toast('Remaining cannot exceed bottle size','error');return}const list=getPerfumes();let editing=false;try{editing=!!window.eval('editingId')}catch(e){}let id=editing?window.eval('editingId'):crypto.randomUUID();const p={id,name:($('name')?.value||'').trim(),brand:($('brand')?.value||'').trim(),type:$('type')?.value||'',profile:'',occasion:$('occasion')?.value||'',cloneOf:($('cloneOf')?.value||'').trim(),imageUrl:($('imageUrl')?.value||'').trim(),quantity:q,quantityRemaining:r,year:parseInt($('year')?.value||'',10)||'',price:n($('price')?.value),rating:$('rating')?.value||'',topNotes:($('topNotes')?.value||'').trim(),heartNotes:($('heartNotes')?.value||'').trim(),baseNotes:($('baseNotes')?.value||'').trim(),accords:($('accords')?.value||'').trim(),sourceUrl:($('sourceUrl')?.value||'').trim(),notes:($('notes')?.value||'').trim()};const old=list.slice();setPerfumes(editing?list.map(x=>String(x.id)===String(id)?{...x,...p}:x):[...list,p]);try{await saveData();toast(editing?'Perfume updated':'Perfume added','success');if(typeof resetForm==='function')resetForm();if(typeof go==='function')go('collection')}catch(err){setPerfumes(old);toast('Could not save: '+(err.message||err),'error')}};

const SOURCES=['All','Designer','Niche','Indian','Middle Eastern'];
let sourceFilter='All';
function sourceOf(p){return String(p.type||'').trim()||'Not set'}
function currentList(){return getPerfumes()}
function filtered(){const list=currentList();return sourceFilter==='All'?list:list.filter(p=>sourceOf(p).toLowerCase()===sourceFilter.toLowerCase())}
function calc(list){const count=list.length,spend=list.reduce((s,p)=>s+n(p.price),0),ml=list.reduce((s,p)=>s+n(p.quantity),0),remaining=list.reduce((s,p)=>s+n(p.quantityRemaining),0),shelf=list.reduce((s,p)=>s+(n(p.quantity)>0?n(p.price)*Math.max(0,Math.min(1,n(p.quantityRemaining)/n(p.quantity))):0),0),brands=new Set(list.map(p=>String(p.brand||'').trim()).filter(Boolean)).size,low=list.filter(p=>n(p.quantity)>0&&n(p.quantityRemaining)/n(p.quantity)<=.25).length,avg=count?spend/count:0,per100=ml?spend/ml*100:0;return{count,spend,ml,remaining,shelf,brands,low,avg,per100}}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function ensureSourceUI(){const stats=$('dCount')?.closest('.stats');if(!stats)return;if(!$('dashboardSourceFilter')){const wrap=document.createElement('div');wrap.id='dashboardSourceFilter';wrap.className='dashboard-source-filter';wrap.innerHTML='<div><strong>View dashboard by source</strong><span>Compare how your collection is distributed across different fragrance sources.</span></div><div class="source-pills">'+SOURCES.map(s=>`<button type="button" class="source-pill ${s==='All'?'active':''}" data-source="${esc(s)}">${esc(s)}</button>`).join('')+'</div>';stats.parentNode.insertBefore(wrap,stats);wrap.querySelectorAll('[data-source]').forEach(b=>b.addEventListener('click',()=>{sourceFilter=b.dataset.source;wrap.querySelectorAll('[data-source]').forEach(x=>x.classList.toggle('active',x===b));refreshDashboard()}))}
if(!$('sourceComparison')){const box=document.createElement('section');box.id='sourceComparison';box.className='source-comparison card';box.innerHTML='<div class="card-head"><div><h3>Source comparison</h3><div class="source-caption">Side-by-side view of your collection by source</div></div><span class="source-selected" id="sourceSelected">All sources</span></div><div class="source-table-wrap"><table class="source-table"><thead><tr><th>Metric</th><th>Designer</th><th>Niche</th><th>Indian</th><th>Middle Eastern</th></tr></thead><tbody id="sourceComparisonBody"></tbody></table></div>';stats.parentNode.insertBefore(box,stats.nextSibling)}}
function refreshDashboard(){const list=filtered(),c=calc(list);setText('dCount',c.count);setText('dRemaining',`${Math.round(c.remaining*10)/10} ml`);setText('dSpend',money(c.spend));setText('dBrands',c.brands);setText('dLowStock',c.low);if($('dTopBrand')){const bc={};list.forEach(p=>bc[p.brand||'Unknown']=(bc[p.brand||'Unknown']||0)+1);const top=Object.entries(bc).sort((a,b)=>b[1]-a[1])[0];setText('dTopBrand',top?top[0]:'—')}setText('sourceSelected',sourceFilter==='All'?'All sources':sourceFilter);const body=$('sourceComparisonBody');if(body)body.innerHTML=['Bottles','Invested','Remaining','Avg. bottle','₹ / 100 ml','Brands','Low stock'].map((label,i)=>{const vals=['Designer','Niche','Indian','Middle Eastern'].map(s=>calc(currentList().filter(p=>sourceOf(p).toLowerCase()===s.toLowerCase())));const fmt=x=>i===0?x.count.toLocaleString('en-IN'):i===1?money(x.spend):i===2?`${Math.round(x.remaining*10)/10} ml`:i===3?money(x.avg):i===4?money(x.per100):i===5?x.brands.toLocaleString('en-IN'):x.low.toLocaleString('en-IN');return`<tr><td>${label}</td>${vals.map(x=>`<td>${fmt(x)}</td>`).join('')}</tr>`}).join('')}
function css(){if($('dashboard-source-css'))return;const s=document.createElement('style');s.id='dashboard-source-css';s.textContent=`#dashboardSourceFilter{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:16px 18px;margin-bottom:14px;background:var(--card);border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow)}#dashboardSourceFilter strong{display:block;font-size:14px}#dashboardSourceFilter span{display:block;color:var(--muted);font-size:11px;margin-top:3px}.source-pills{display:flex;gap:6px;flex-wrap:wrap}.source-pill{border:1px solid var(--line);background:var(--soft);color:var(--muted);padding:8px 12px;border-radius:999px;font-size:11px;font-weight:900}.source-pill.active{background:var(--ink);border-color:var(--ink);color:#fff}.source-comparison{margin:0 0 18px;overflow:hidden}.source-caption{color:var(--muted);font-size:11px;margin-top:3px}.source-selected{font-size:11px;font-weight:900;background:var(--soft);padding:7px 10px;border-radius:999px;color:var(--accent)}.source-table-wrap{overflow:auto}.source-table{width:100%;border-collapse:collapse;min-width:720px}.source-table th,.source-table td{padding:12px 14px;border-bottom:1px solid var(--line);font-size:12px;text-align:right;white-space:nowrap}.source-table th:first-child,.source-table td:first-child{text-align:left}.source-table th{background:#fbf8f3;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.06em}.source-table tbody tr:last-child td{border-bottom:0}.source-table tbody tr:hover td{background:#fffaf5}@media(max-width:760px){#dashboardSourceFilter{display:block}.source-pills{margin-top:12px;overflow-x:auto;flex-wrap:nowrap;padding-bottom:2px}.source-pill{flex:0 0 auto}}`;document.head.appendChild(s)}
const oldRender=window.renderDashboard;window.renderDashboard=function(){if(typeof oldRender==='function')oldRender();ensureSourceUI();refreshDashboard()};
css();

/* Mobile bottom navigation is fixed over the page. Add enough scroll clearance so
   the final perfume card's View/Edit buttons can always be brought above it. */
function fixMobileBottomClearance(){
  if($('mobile-bottom-clearance-css'))return;
  const s=document.createElement('style');
  s.id='mobile-bottom-clearance-css';
  s.textContent=`@media(max-width:760px){main{padding-bottom:170px!important}.mobile-bar{z-index:1000}}`;
  document.head.appendChild(s);
}
fixMobileBottomClearance();
setTimeout(()=>{try{ensureSourceUI();refreshDashboard()}catch(e){console.error('Dashboard enhancement',e)}},0);
window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{ensureSourceUI();refreshDashboard();fixMobileBottomClearance()},100));
})();