/* Cloud sync for My Perfume Collection - compatible with the updated HTML app. */
(function () {
  'use strict';
  const SUPABASE_URL = 'https://hlhvzgaedcwprvactlwm.supabase.co';
  const SUPABASE_KEY = 'sb_publishable_tkI9iZMT722qLWYflXtxjw_98Qolbmx';
  let sb = null;
  let currentUser = null;
  let busy = false;
  const original = {};
  function q(id){return document.getElementById(id)}
  function notify(msg,type='info'){if(typeof toast==='function'){toast(msg);return}console[type==='error'?'error':'log'](msg)}
  function addGateStyles(){if(q('cloud-sync-styles'))return;const s=document.createElement('style');s.id='cloud-sync-styles';s.textContent='.cloud-gate{position:fixed;inset:0;z-index:10000;background:rgba(247,244,239,.98);display:flex;align-items:center;justify-content:center;padding:20px}.cloud-box{width:min(460px,100%);background:#fff;border:1px solid #e5ded6;border-radius:22px;padding:28px;box-shadow:0 20px 70px rgba(60,45,30,.14)}.cloud-box h2{margin:0 0 6px}.cloud-box p{color:#746b63;font-size:14px;line-height:1.5}.cloud-box label{display:block;font-size:12px;font-weight:700;color:#746b63;margin:10px 0 5px}.cloud-box input{width:100%;border:1px solid #e5ded6;border-radius:10px;padding:11px;outline:none}.cloud-box input.invalid{border-color:#b84949;background:#fffafa}.cloud-box .cloud-row{display:flex;gap:8px;margin-top:14px}.cloud-box button{border:1px solid #e5ded6;background:#fff;border-radius:10px;padding:10px 13px;flex:1;font-weight:700;cursor:pointer}.cloud-box button.primary{background:#24201c;color:#fff;border-color:#24201c}.cloud-box button:disabled{opacity:.55;cursor:not-allowed}.cloud-help{font-size:11px;color:#8a8179;margin-top:6px;line-height:1.4}.cloud-status{font-size:13px;margin-top:12px;line-height:1.45;padding:9px;border-radius:10px;background:#f6f3ef;color:#62584f;min-height:20px}.cloud-status.success{color:#237a45;background:#edf8f1;border:1px solid #cfe9d8}.cloud-status.error{color:#9b3434;background:#fff2f2;border:1px solid #efcaca}.cloud-user{position:fixed;right:18px;top:78px;z-index:25;display:flex;gap:7px;align-items:center;background:#fff;border:1px solid #e5ded6;border-radius:999px;padding:6px 9px 6px 11px;font-size:12px;box-shadow:0 5px 18px rgba(60,45,30,.08)}.cloud-user button{border:0;background:#24201c;color:#fff;border-radius:999px;padding:6px 9px;font-size:11px;cursor:pointer}';document.head.appendChild(s)}
  function showGate(){if(q('cloudGate'))return;const d=document.createElement('div');d.id='cloudGate';d.className='cloud-gate';d.innerHTML='<div class="cloud-box"><h2>My Perfume Collection</h2><p>Your collection is cloud-backed. Sign in or create an account to use the same collection across devices.</p><label for="cloudEmail">Email address</label><input id="cloudEmail" type="email" autocomplete="email" placeholder="you@example.com"><div id="cloudEmailHelp" class="cloud-help">Use an email address you can access.</div><label for="cloudPassword">Password</label><input id="cloudPassword" type="password" autocomplete="current-password" placeholder="At least 6 characters"><div id="cloudPasswordHelp" class="cloud-help">Minimum 6 characters.</div><div class="cloud-row"><button type="button" class="primary" id="cloudLogin">Sign in</button><button type="button" id="cloudSignup">Create account</button></div><div id="cloudStatus" class="cloud-status" aria-live="polite"></div></div>';document.body.appendChild(d);const email=q('cloudEmail'),pass=q('cloudPassword');email.oninput=()=>{email.classList.remove('invalid');q('cloudEmailHelp').textContent='Use an email address you can access.'};pass.oninput=()=>{pass.classList.remove('invalid');q('cloudPasswordHelp').textContent='Minimum 6 characters.'};email.onkeydown=e=>{if(e.key==='Enter')authenticate('login')};pass.onkeydown=e=>{if(e.key==='Enter')authenticate('login')};q('cloudLogin').onclick=()=>authenticate('login');q('cloudSignup').onclick=()=>authenticate('signup')}
  function setStatus(text,type=''){const el=q('cloudStatus');if(!el)return;el.className='cloud-status '+type;el.textContent=text}
  function validateAuth(){const email=q('cloudEmail'),pass=q('cloudPassword');let ok=true;if(!/^\S+@\S+\.\S+$/.test(email.value.trim())){email.classList.add('invalid');q('cloudEmailHelp').textContent='Enter a valid email address.';ok=false}if(pass.value.length<6){pass.classList.add('invalid');q('cloudPasswordHelp').textContent='Password must be at least 6 characters.';ok=false}return ok}
  function friendlyAuthError(err,mode){const m=String(err?.message||err||'').toLowerCase();if(m.includes('user already registered')||m.includes('already been registered'))return'An account with this email already exists. Please use Sign in.';if(m.includes('invalid login credentials'))return'Email or password is incorrect.';if(m.includes('email not confirmed'))return'Please confirm your email address before signing in.';if(m.includes('rate limit')||m.includes('too many'))return'Too many attempts. Please wait a few minutes and try again.';return mode==='signup'?'We could not create the account. '+(err?.message||'Please try again.'): 'We could not sign you in. '+(err?.message||'Please try again.')}
  async function loadSupabase(){if(window.supabase){sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return}await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=()=>reject(new Error('Could not load Supabase.'));document.head.appendChild(s)});sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY)}
  function isUuid(id){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(id||''))}
  function toRow(p){if(!isUuid(p.id))p.id=crypto.randomUUID();return{id:p.id,user_id:currentUser.id,name:p.name,brand:p.brand,type:p.type||null,occasion:p.occasion||null,clone_of:p.cloneOf||null,image:p.imageUrl||p.image||null,volume:Number(p.quantity??p.volume)||0,remaining:Number(p.quantityRemaining??p.remaining)||0,year:p.year?Number(p.year):null,price:Number(p.price)||0,rating:p.rating!==''&&p.rating!=null?Number(p.rating):null,top_notes:p.topNotes||null,heart_notes:p.heartNotes||null,base_notes:p.baseNotes||null,accords:p.accords||null,source:p.sourceUrl||p.source||null,my_notes:p.notes||p.myNotes||null,updated_at:new Date().toISOString()}}
  function fromRow(r){return{id:r.id,name:r.name,brand:r.brand,type:r.type||'',occasion:r.occasion||'',cloneOf:r.clone_of||'',imageUrl:r.image||'',quantity:Number(r.volume)||0,quantityRemaining:Number(r.remaining)||0,year:r.year||'',price:Number(r.price)||0,profile:'',topNotes:r.top_notes||'',heartNotes:r.heart_notes||'',baseNotes:r.base_notes||'',accords:r.accords||'',sourceUrl:r.source||'',notes:r.my_notes||''}}
  async function fetchCloud(){const{data,error}=await sb.from('perfumes').select('*').order('created_at',{ascending:true});if(error)throw error;return data||[]}
  async function replaceCloud(items){const{error:delError}=await sb.from('perfumes').delete().eq('user_id',currentUser.id);if(delError)throw delError;if(!items.length)return;const{error}=await sb.from('perfumes').insert(items.map(toRow));if(error)throw error}
  function redraw(){try{if(typeof populateFilters==='function')populateFilters()}catch(e){console.warn(e)}try{if(typeof renderCollection==='function')renderCollection()}catch(e){console.warn(e)}try{if(typeof renderDashboard==='function')renderDashboard()}catch(e){console.warn(e)}}
  async function syncNow(){if(!currentUser)return;try{if(typeof perfumes==='undefined'||!Array.isArray(perfumes))throw new Error('Local collection state is unavailable.');localStorage.setItem('perfumeCollection_v2',JSON.stringify(perfumes));await replaceCloud(perfumes);redraw()}catch(e){notify('Saved locally, but cloud sync failed: '+(e.message||e),'error')}}
  function installWrappers(){if(typeof savePerfume==='function'&&!original.savePerfume){original.savePerfume=savePerfume;window.savePerfume=function(e){original.savePerfume(e);setTimeout(syncNow,0)}}if(typeof deletePerfume==='function'&&!original.deletePerfume){original.deletePerfume=deletePerfume;window.deletePerfume=function(id){original.deletePerfume(id);setTimeout(syncNow,0)}}if(typeof commitImport==='function'&&!original.commitImport){original.commitImport=commitImport;window.commitImport=function(){original.commitImport();setTimeout(syncNow,0)}}}
  async function boot(){const{data,error}=await sb.auth.getUser();if(error)throw error;currentUser=data.user;if(!currentUser){showGate();return}const cloud=await fetchCloud();const local=(typeof perfumes!=='undefined'&&Array.isArray(perfumes))?perfumes:[];if(cloud.length===0&&local.length>0){const ok=confirm('Your cloud collection is empty, but this browser has an existing perfume collection. Upload it to your account?');if(ok){local.forEach(p=>{if(!isUuid(p.id))p.id=crypto.randomUUID()});await replaceCloud(local)}else{perfumes=[]}}else{perfumes=cloud.map(fromRow)}localStorage.setItem('perfumeCollection_v2',JSON.stringify(perfumes||[]));installWrappers();redraw();const gate=q('cloudGate');if(gate)gate.remove();const old=q('cloudUser');if(old)old.remove();const badge=document.createElement('div');badge.id='cloudUser';badge.className='cloud-user';badge.innerHTML='<span>'+String(currentUser.email).replace(/[&<>"\']/g,'')+'</span><button type="button" id="cloudLogout">Sign out</button>';document.body.appendChild(badge);q('cloudLogout').onclick=async()=>{await sb.auth.signOut();location.reload()}}
  async function authenticate(mode){if(busy)return;if(!validateAuth()){setStatus('Please fix the highlighted fields and try again.','error');return}busy=true;const login=q('cloudLogin'),signup=q('cloudSignup');login.disabled=true;signup.disabled=true;const email=q('cloudEmail').value.trim(),password=q('cloudPassword').value;setStatus(mode==='login'?'Signing in…':'Creating your account…');try{let result;if(mode==='login')result=await sb.auth.signInWithPassword({email,password});else{const redirect=new URL(location.href);redirect.search='';redirect.hash='';result=await sb.auth.signUp({email,password,options:{emailRedirectTo:redirect.toString()}})}if(result.error)throw result.error;if(mode==='signup'&&!result.data.session){setStatus('Account created successfully. A confirmation email was sent to '+email+'. Click the link, then return here and sign in.','success')}else{setStatus('Signed in. Loading your collection…','success');await boot()}}catch(e){setStatus(friendlyAuthError(e,mode),'error')}finally{busy=false;login.disabled=false;signup.disabled=false}}
  async function start(){addGateStyles();try{await loadSupabase();const{data}=await sb.auth.getSession();sb.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')location.reload()});if(data.session)await boot();else showGate()}catch(e){showGate();setStatus(e.message||'Could not connect to Supabase.','error')}}
  window.addEventListener('load',start);
})();
