/* Cloud sync layer for My Perfume Collection */
(function(){
  const SUPABASE_URL='https://hlhvzgaedcwprvactlwm.supabase.co';
  const SUPABASE_KEY='sb_publishable_tkI9iZMT722qLWYflXtxjw_98Qolbmx';
  const SCRIPT_ID='supabase-js-cdn';
  let sb; let sessionUser=null; let originalSave=null; let authBusy=false;
  function loadClient(){return new Promise((resolve,reject)=>{if(window.supabase){sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return resolve(sb)}const s=document.createElement('script');s.id=SCRIPT_ID;s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>{try{sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);resolve(sb)}catch(e){reject(e)}};s.onerror=()=>reject(new Error('Could not load the Supabase client. Please check your internet connection and refresh.'));document.head.appendChild(s)})}
  function addStyles(){const s=document.createElement('style');s.textContent='.cloud-gate{position:fixed;inset:0;background:rgba(247,244,239,.98);z-index:100;display:flex;align-items:center;justify-content:center;padding:20px}.cloud-box{width:min(460px,100%);background:#fff;border:1px solid #e5ded6;border-radius:22px;padding:28px;box-shadow:0 20px 70px rgba(60,45,30,.14)}.cloud-box h2{margin:0 0 6px}.cloud-box p{color:#746b63;font-size:14px;line-height:1.5}.cloud-box label{display:block;font-size:12px;font-weight:700;color:#746b63;margin:10px 0 5px}.cloud-box input{width:100%;border:1px solid #e5ded6;border-radius:10px;padding:11px;outline:none}.cloud-box input.invalid{border-color:#b84949;background:#fffafa}.cloud-box .row{display:flex;gap:8px;margin-top:14px}.cloud-box button{border:1px solid #e5ded6;background:#fff;border-radius:10px;padding:10px 13px;flex:1;font-weight:700;cursor:pointer}.cloud-box button.primary{background:#24201c;color:#fff;border-color:#24201c}.cloud-box button:disabled{opacity:.55;cursor:not-allowed}.cloud-help{font-size:11px;color:#8a8179;margin-top:6px}.cloud-status{font-size:13px;margin-top:12px;line-height:1.45;padding:0}.cloud-status.success{color:#237a45;background:#edf8f1;border:1px solid #cfe9d8;border-radius:10px;padding:9px}.cloud-status.error{color:#9b3434;background:#fff2f2;border:1px solid #efcaca;border-radius:10px;padding:9px}.cloud-user{position:fixed;right:18px;top:78px;z-index:25;display:flex;gap:7px;align-items:center;background:#fff;border:1px solid #e5ded6;border-radius:999px;padding:6px 9px 6px 11px;font-size:12px;box-shadow:0 5px 18px rgba(60,45,30,.08)}.cloud-user button{border:0;background:#24201c;color:#fff;border-radius:999px;padding:6px 9px;font-size:11px;cursor:pointer}';document.head.appendChild(s)}
  function gate(){if(document.getElementById('cloudGate'))return;const d=document.createElement('div');d.className='cloud-gate';d.id='cloudGate';d.innerHTML='<div class="cloud-box"><h2>My Perfume Collection</h2><p>Your collection is cloud-backed. Create an account or sign in to access it from any device.</p><label for="cloudEmail">Email address</label><input id="cloudEmail" type="email" autocomplete="email" placeholder="you@example.com"><div class="cloud-help" id="cloudEmailHelp">Use an email address you can access.</div><label for="cloudPassword">Password</label><input id="cloudPassword" type="password" autocomplete="current-password" placeholder="At least 6 characters"><div class="cloud-help" id="cloudPasswordHelp">Minimum 6 characters.</div><div class="row"><button type="button" class="primary" id="cloudLogin">Sign in</button><button type="button" id="cloudSignup">Create account</button></div><div class="cloud-status" id="cloudStatus"></div></div>';document.body.appendChild(d);const email=document.getElementById('cloudEmail'),pw=document.getElementById('cloudPassword');email.oninput=()=>{email.classList.remove('invalid');document.getElementById('cloudEmailHelp').textContent='Use an email address you can access.'};pw.oninput=()=>{pw.classList.remove('invalid');document.getElementById('cloudPasswordHelp').textContent='Minimum 6 characters.'};email.onkeydown=e=>{if(e.key==='Enter')auth('login')};pw.onkeydown=e=>{if(e.key==='Enter')auth('login')};document.getElementById('cloudLogin').onclick=()=>auth('login');document.getElementById('cloudSignup').onclick=()=>auth('signup')}
  function status(t,type=''){const e=document.getElementById('cloudStatus');if(!e)return;e.className='cloud-status '+type;e.textContent=t}
  function validate(){const e=document.getElementById('cloudEmail'),p=document.getElementById('cloudPassword');let ok=true;if(!/^\S+@\S+\.\S+$/.test(e.value.trim())){e.classList.add('invalid');document.getElementById('cloudEmailHelp').textContent='Enter a valid email address.';ok=false}if(p.value.length<6){p.classList.add('invalid');document.getElementById('cloudPasswordHelp').textContent='Password must be at least 6 characters.';ok=false}return ok}
  function friendly(e,mode){const m=String(e?.message||e||'').toLowerCase();if(m.includes('user already registered')||m.includes('already been registered'))return'An account with this email already exists. Please use Sign in instead.';if(m.includes('invalid login credentials'))return'Email or password is incorrect. Please check both and try again.';if(m.includes('email not confirmed'))return'Your email is not confirmed yet. Please check your inbox.';if(m.includes('redirect')||m.includes('url'))return'The account was created, but the confirmation redirect is not configured in Supabase yet.';if(m.includes('rate limit')||m.includes('too many'))return'Too many attempts. Please wait a few minutes and try again.';return mode==='signup'?'We could not create the account. '+(e?.message||'Please try again.'):'We could not sign you in. '+(e?.message||'Please try again.')}
  async function auth(mode){if(authBusy)return;if(!validate()){status('Please fix the highlighted fields and try again.','error');return}authBusy=true;const login=document.getElementById('cloudLogin'),signup=document.getElementById('cloudSignup');login.disabled=true;signup.disabled=true;status(mode==='login'?'Signing in…':'Creating your account…');try{const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPassword').value;let result;if(mode==='login')result=await sb.auth.signInWithPassword({email,password});else{const redirectTo=new URL(location.href);redirectTo.search='';redirectTo.hash='';result=await sb.auth.signUp({email,password,options:{emailRedirectTo:redirectTo.toString()}})}if(result.error)throw result.error;if(mode==='signup'&&!result.data.session){status('Account created successfully. A confirmation email has been sent to '+email+'. Click the link in that email, then return here and sign in.','success');return}status('Sign-in successful. Loading your collection…','success');await boot(result.data?.session)}catch(e){status(friendly(e,mode),'error')}finally{authBusy=false;login.disabled=false;signup.disabled=false}}
  function userBadge(){const old=document.getElementById('cloudUser');if(old)old.remove();const d=document.createElement('div');d.id='cloudUser';d.className='cloud-user';d.innerHTML='<span>'+esc(sessionUser.email||'Signed in')+'</span><button type="button" id="cloudLogout">Sign out</button>';document.body.appendChild(d);document.getElementById('cloudLogout').onclick=()=>sb.auth.signOut()}
  function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function toRow(p){return{id:p.id,user_id:sessionUser.id,name:p.name,brand:p.brand,type:p.type||null,occasion:p.occasion||null,clone_of:p.cloneOf||null,image:p.image||null,volume:Number(p.volume)||0,remaining:Number(p.remaining)||0,year:p.year?Number(p.year):null,price:Number(p.price)||0,rating:p.rating!==''&&p.rating!=null?Number(p.rating):null,top_notes:p.topNotes||null,heart_notes:p.heartNotes||null,base_notes:p.baseNotes||null,accords:p.accords||null,source:p.source||null,my_notes:p.myNotes||null,updated_at:new Date().toISOString()}}
  function fromRow(r){return{id:r.id,name:r.name,brand:r.brand,type:r.type||'',occasion:r.occasion||'',cloneOf:r.clone_of||'',image:r.image||'',volume:Number(r.volume)||0,remaining:Number(r.remaining)||0,year:r.year||'',price:Number(r.price)||0,rating:r.rating==null?'':r.rating,topNotes:r.top_notes||'',heartNotes:r.heart_notes||'',baseNotes:r.base_notes||'',accords:r.accords||'',source:r.source||'',myNotes:r.my_notes||''}}
  async function fetchCloud(){const{data,error}=await sb.from('perfumes').select('*').order('created_at',{ascending:true});if(error)throw error;return data||[]}
  async function replaceCloud(items){const{error:delErr}=await sb.from('perfumes').delete().eq('user_id',sessionUser.id);if(delErr)throw delErr;if(items.length){const{error}=await sb.from('perfumes').insert(items.map(toRow));if(error)throw error}}
  function redraw(){try{if(typeof refreshAll==='function'){refreshAll();return}if(typeof refreshCollection==='function')refreshCollection();if(typeof refreshDashboard==='function')refreshDashboard();if(typeof renderCollection==='function')renderCollection();if(typeof renderDashboard==='function')renderDashboard();if(typeof populateFilters==='function')populateFilters()}catch(e){console.error('UI refresh failed',e)}}
  async function cloudSave(){try{if(typeof collection==='undefined')throw new Error('Collection state is unavailable. Please refresh the page.');localStorage.setItem('perfumeCollection.v10',JSON.stringify(collection));await replaceCloud(collection);redraw()}catch(e){if(typeof toast==='function')toast('Cloud save failed: '+(e.message||e));else console.error(e)}}
  async function boot(){sessionUser=(await sb.auth.getUser()).data.user;if(!sessionUser)return;userBadge();try{const cloud=await fetchCloud();if(cloud.length===0&&Array.isArray(window.collection)&&collection.length>0){if(confirm('I found your existing browser collection. Upload it to your new cloud account?')){await replaceCloud(collection);if(typeof toast==='function')toast('Existing collection uploaded to cloud.')}else collection=[]}else if(Array.isArray(cloud)){collection=cloud.map(fromRow)}localStorage.setItem('perfumeCollection.v10',JSON.stringify(collection));redraw();if(typeof save==='function'&&originalSave===null){originalSave=save;save=cloudSave}else if(originalSave===null){window.cloudSave=cloudSave}const gate=document.getElementById('cloudGate');if(gate)gate.remove()}catch(e){status('Signed in, but your collection could not be loaded: '+(e.message||e),'error')}}
  async function start(){addStyles();try{await loadClient();const{data}=await sb.auth.getSession();sb.auth.onAuthStateChange((event,s)=>{if(event==='SIGNED_IN'&&s)boot(s).catch(e=>status(e.message,'error'));if(event==='SIGNED_OUT'){sessionUser=null;location.reload()}});if(data.session)await boot(data.session);else gate()}catch(e){gate();status(e.message||'Supabase connection failed. Please refresh and try again.','error')}}
  window.addEventListener('load',start)
})();