/* Weather + time-of-day enhancement */
(function(){
const W=["Summer","Monsoon","Winter"],T=["Daytime","Evening","Night"];
const q=id=>document.getElementById(id),ev=n=>{try{return window.eval(n)}catch(e){return null}},set=(n,v)=>{try{window.__wt=v;window.eval(n+'=window.__wt');delete window.__wt}catch(e){console.error(e)}},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=()=>{const x=ev('perfumes');return Array.isArray(x)?x:[]},parse=v=>String(v||'').split(/\s*,\s*/).filter(Boolean);
function inject(){
 if(!q('whenWearFields')){const f=q('perfumeForm');if(!f)return;const s=document.createElement('div');s.id='whenWearFields';s.className='form-section';const checks=a=>a.map(x=>`<label class="wt-check"><input type="checkbox" value="${esc(x)}">${esc(x)}</label>`).join('');s.innerHTML=`<h4>When to wear</h4><div class="wt-cols"><div><div class="wt-label">Weather</div><div id="wtWeather" class="wt-options">${checks(W)}</div></div><div><div class="wt-label">Time of day</div><div id="wtTime" class="wt-options">${checks(T)}</div></div></div>`;const first=f.querySelector('.form-section');first?first.parentNode.insertBefore(s,first):f.appendChild(s)}
 const filters=document.querySelector('.filters');if(filters&&!q('filterWeather')){const a=document.createElement('div');a.className='field';a.innerHTML='<label>Weather</label><select id="filterWeather"><option value="">All weather</option>'+W.map(x=>`<option>${x}</option>`).join('')+'</select>';filters.appendChild(a);const b=document.createElement('div');b.className='field';b.innerHTML='<label>Time of day</label><select id="filterTime"><option value="">Any time</option>'+T.map(x=>`<option>${x}</option>`).join('')+'</select>';filters.appendChild(b);a.querySelector('select').onchange=()=>window.renderCollection();b.querySelector('select').onchange=()=>window.renderCollection()}
}
const checked=id=>[...document.querySelectorAll('#'+id+' input:checked')].map(x=>x.value).join(', '),setChecked=(id,v)=>{const s=new Set(parse(v));document.querySelectorAll('#'+id+' input').forEach(x=>x.checked=s.has(x.value))};
async function load(){inject();const sb=ev('sb'),u=ev('currentUser');if(!sb||!u)return;const r=await sb.from('perfumes').select('id,weather,time_of_day').eq('user_id',u.id);if(r.error)throw r.error;const m=new Map((r.data||[]).map(x=>[String(x.id),x]));set('perfumes',arr().map(p=>{const x=m.get(String(p.id));return x?{...p,weather:x.weather||'',timeOfDay:x.time_of_day||''}:p}));if(window.renderCollection)window.renderCollection();if(window.renderDashboard)window.renderDashboard()}
const oldH=window.hydrateCloud;if(typeof oldH==='function')window.hydrateCloud=async function(){const r=await oldH.apply(this,arguments);try{await load()}catch(e){console.error('Weather/time load',e)}return r};
const oldE=window.editPerfume;window.editPerfume=function(id){const p=arr().find(x=>String(x.id)===String(id));if(!p)return oldE&&oldE(id);set('editingId',p.id);['name','brand','type','occasion','cloneOf','imageUrl','quantity','quantityRemaining','year','price','rating','topNotes','heartNotes','baseNotes','accords','sourceUrl','notes'].forEach(k=>{const e=q(k);if(e)e.value=p[k]??''});setChecked('wtWeather',p.weather);setChecked('wtTime',p.timeOfDay);if(q('formTitle'))q('formTitle').textContent='Edit perfume';if(q('saveBtn'))q('saveBtn').textContent='Update perfume';if(window.updateCost)window.updateCost();window.go('add')};
const oldA=window.startAdd;window.startAdd=function(){if(oldA)oldA();setChecked('wtWeather','');setChecked('wtTime','');if(q('formTitle'))q('formTitle').textContent='Add a perfume';if(q('saveBtn'))q('saveBtn').textContent='Save perfume'};
window.savePerfume=async function(e){e.preventDefault();const f=q('perfumeForm');if(!f||!f.reportValidity())return;const qty=Number(q('quantity')?.value)||0,rem=Number(q('quantityRemaining')?.value)||0;if(rem>qty){q('quantityRemaining').setCustomValidity('Remaining cannot exceed bottle size');f.reportValidity();return}q('quantityRemaining').setCustomValidity('');const sb=ev('sb'),u=ev('currentUser'),editing=ev('editingId'),id=editing||crypto.randomUUID(),old=arr();const p={id,user_id:u.id,name:q('name')?.value.trim(),brand:q('brand')?.value.trim(),type:q('type')?.value||null,occasion:q('occasion')?.value||null,clone_of:q('cloneOf')?.value.trim()||null,image:q('imageUrl')?.value.trim()||null,volume:qty,remaining:rem,year:Number(q('year')?.value)||null,price:Number(q('price')?.value)||0,rating:q('rating')?.value||null,top_notes:q('topNotes')?.value.trim()||null,heart_notes:q('heartNotes')?.value.trim()||null,base_notes:q('baseNotes')?.value.trim()||null,accords:q('accords')?.value.trim()||null,source:q('sourceUrl')?.value.trim()||null,my_notes:q('notes')?.value.trim()||null,weather:checked('wtWeather')||null,time_of_day:checked('wtTime')||null,updated_at:new Date().toISOString()};try{const r=editing?await sb.from('perfumes').update(p).eq('id',id).eq('user_id',u.id):await sb.from('perfumes').insert(p);if(r.error)throw r.error;const local={id,name:p.name,brand:p.brand,type:p.type,occasion:p.occasion,cloneOf:p.clone_of,imageUrl:p.image,quantity:qty,quantityRemaining:rem,year:p.year,price:p.price,rating:p.rating,topNotes:p.top_notes,heartNotes:p.heart_notes,baseNotes:p.base_notes,accords:p.accords,sourceUrl:p.source,notes:p.my_notes,weather:p.weather||'',timeOfDay:p.time_of_day||''};set('perfumes',editing?old.map(x=>String(x.id)===String(id)?{...x,...local}:x):[...old,local]);set('editingId',null);window.resetForm();window.go('collection');window.renderCollection();window.renderDashboard();window.toast(editing?'Perfume updated':'Perfume added','success')}catch(err){console.error(err);window.toast('Could not save: '+(err.message||err),'error')}};
window.deletePerfume=async function(id){const p=arr().find(x=>String(x.id)===String(id));if(!p||!confirm(`Delete “${p.name}” from your collection?`))return;const sb=ev('sb'),u=ev('currentUser');try{const r=await sb.from('perfumes').delete().eq('id',id).eq('user_id',u.id);if(r.error)throw r.error;set('perfumes',arr().filter(x=>String(x.id)!==String(id)));window.renderCollection();window.renderDashboard();window.toast('Perfume deleted','success')}catch(e){window.toast('Delete failed: '+e.message,'error')}};
const oldF=window.filtered;if(typeof oldF==='function')window.filtered=function(){const a=oldF(),w=q('filterWeather')?.value||'',t=q('filterTime')?.value||'';return a.filter(p=>(!w||parse(p.weather).includes(w))&&(!t||parse(p.timeOfDay).includes(t)))};
const oldC=window.cardHTML;if(typeof oldC==='function')window.cardHTML=function(p){return oldC(p).replace('<div class="metrics">',`<div class="meta-row"><span class="chip">${esc(p.weather||'Weather not set')}</span><span class="chip">${esc(p.timeOfDay||'Time not set')}</span></div><div class="metrics">`)};
const style=document.createElement('style');style.textContent='.wt-cols{display:grid;grid-template-columns:1fr 1fr;gap:18px}.wt-label{font-size:11px;text-transform:uppercase;letter-spacing:.07em;font-weight:900;color:var(--muted);margin-bottom:7px}.wt-options{display:flex;gap:7px;flex-wrap:wrap}.wt-check{display:inline-flex;align-items:center;gap:6px;padding:8px 10px;border:1px solid var(--line);border-radius:10px;background:#fffdfb;font-size:12px;font-weight:800}.wt-check input{accent-color:var(--accent)}@media(max-width:760px){.wt-cols{grid-template-columns:1fr}}';document.head.appendChild(style);inject();window.addEventListener('load',()=>setTimeout(()=>load().catch(e=>console.error(e)),900));
})();